### ISSUE TITLE
WebGL - add glow effect on lines

### ISSUE THREAD

**Issue by Matthi0uw** [anvaka/VivaGraphJS#103]
Hi,
I would like to display glow effect on links like [here](http://armsglobe.chromeexperiments.com/).
Have you any idea to add this kind of effect ?
Thanks

**Comment by anvaka** [comment]
You would have to write custom shader inside [webglLinkProgram](https://github.com/anvaka/VivaGraphJS/blob/ea49da27c777aa2302efd697200a14d915008f48/src/WebGL/webglLinkProgram.js), similar to [this demo](https://github.com/anvaka/VivaGraphJS/blob/master/demos/other/webglCustomNode.html).

However it's not very easy. I can highly recommend switching to `ngraph` modules, and considering THREE.js as rendering engine. 

You can find an example of using `three.js` and `ngraph` here: [Big bang of npm](https://github.com/anvaka/allnpmviz3d#big-bang-of-npm). You also don't necessary have to use 3D layout. `ngraph` is like Lego where you can choose parts which you like and create your own custom library.
