### ISSUE TITLE
Text labels in webgl

### ISSUE THREAD

**Issue by anvaka** [anvaka/VivaGraphJS#105]
Currently there is no way to render text labels in webgl. It would be great to have it.

**Comment by anvaka** [comment]
This is a duplicate of https://github.com/anvaka/VivaGraphJS/issues/86

**Comment by danpaulsmith** [comment]
If there's a custom shader for a WebGLNodeProgram, then potentially a shader can also be used to render a glyph, and therefore a set of glyphs. Will have to try at some point
