### ISSUE TITLE
SVG nodes, text and links no longer displaying

### ISSUE THREAD

**Issue by alexge233** [anvaka/VivaGraphJS#108]
Let me explain:

I extensively use VivaGraph Js, (version 4.x) and recently I did an upgrade of my Debian Wheezy to Jessie. After that, SVG stopped working. I tried downgrading chromium and chrome, but I think this is a rendering issue, so it has to do with the underlying mechanisms in Webkit or some other library.

WebGL nodes and links work fine, but SVG is no longer visible, yet upon inspection of the elements in the browser, they are still there, just not showing.
I have since upgraded to VivaGraph 0.5.8, but the problem still persists.
This is absolutely crucial for me to solve, I would really appreciate any help regarding this.

Chromium Version 37.0.2062.120 Built on Debian 7.6, running on Debian jessie/sid (281580) (64-bit).
Same issue with Chrome 38, and Iceweasel (Firefox) 31.1.0

**Comment by seinecle** [comment]
For anyone struggling with this, I got an ok effect with this:

```
#graphDiv > svg {
        width: 100%;
        height: 100%;
        min-height: 250px;
}


```
where graphDiv is the id of the `div` where you put your graph
