### ISSUE TITLE
WebGL - disable renderer auto-pause

### ISSUE THREAD

**Issue by provolot** [anvaka/VivaGraphJS#111]
Is it possible to disable the renderer auto-pause? I think it's helpful functionality, but I want it to go on forever. I suppose that I could continually call renderer.resume(), but can I just disable it altogether?

**Comment by anvaka** [comment]
@gg4u has a good point. Rendering forever is not generally a good idea. But I think you can achieve it by running your own RequestAnimationFrame loop:

``` javascript
function onFrame() {
  requestAnimationFrame(onFrame); // schedule next frame
  renderer.resume(); // never let renderer stop
}
```

Please let me know if this doesn't works.
