### ISSUE TITLE
Getting data on nodes and links

### ISSUE THREAD

**Issue by richa2008** [anvaka/VivaGraphJS#112]
Hi,
I am using Vivagraph.js for creating a network which contains around 5000 nodes and links.I want to display data on only those nodes which are present inside the viewport. How can I do this???

**Comment by richa2008** [comment]
Okay...Can I divide my diagram into clusters so that,on clicking or hovering on any cluster will result in the data display of the nodes present in that cluster.If so,how can I do that.Please help...

**Comment by anvaka** [comment]
It would really depend on your data. Out of the box VivaGraph does not support automatic clustering.
