### ISSUE TITLE
Absolute position of node

### ISSUE THREAD

**Issue by demarc11** [anvaka/VivaGraphJS#113]
This may be a somewhat simple question, but I've been banging my head against it without success, so here goes: 

I need to get the absolute position of a node. I know how to use layout.getNodePosition(node.id), but this returns the position relative to some central point.  Is there anyway to get the position of a node either relative to the page as a whole or to the <div> containing the graph?

**Comment by demarc11** [comment]
Thank you very much!  That worked beautifully.

**Comment by anvaka** [comment]
Glad it worked!
