### ISSUE TITLE
Center Vivagraph wrapping div on node

### ISSUE THREAD

**Issue by MarioVillani** [anvaka/VivaGraphJS#114]
Hi,
i'm showing a Vivagraph graph in a Bootstrap modal.
This is my markup
```html
<div class="modal-content">
	<div class="modal-header">
		<button type="button" class="close" data-dismiss="modal" aria-hidden="true">
			×
		</button>
		<h4 class="modal-title">Info</h4>
	</div>
	<div class="modal-body"><div id="graph1"></div></div>
	<div class="modal-footer">
		<button data-dismiss="modal" class="button" type="button">Cancel</button>
		<button type="button" class="button">Ok</button>
	</div>
</div>
```

Graph 1 CSS:
```css
#graph1 {
    height: 600px;
    width: 562px;
}
```

When graph is painted, i would like center the viewing area on a certain node painted.
Actually i need to click and drag in the modal body to view the graph correctly.
Is there a way to fix this? How can i center the current view on a node?Thanks.

**Comment by anvaka** [comment]
Hi Mario. 

Would [this](https://github.com/anvaka/VivaGraphJS/blob/9a01a98fcf880f11714d2f88d8f7b8bbd9c912a1/demos/other/zoomPanAPI.html#L40-L42) work? 

``` js
var pos = layout.getNodePosition(nodeId);
renderer.moveTo(pos.x, pos.y);
```

**Comment by anvaka** [comment]
Resolving this.
