### ISSUE TITLE
images not coming

### ISSUE THREAD

**Issue by richa2008** [anvaka/VivaGraphJS#116]
Hi..
I am using webgl rendering to display around 5k nodes.But the images which I am putting for nodes is not coming for all the nodes.Only some nodes are getting displayed with the images and the rest are coming with green square nodes.Please help.

**Comment by anvaka** [comment]
Do you have a demo which you can put to http://jsbin.com/ ?

**Comment by anvaka** [comment]
I don't see the graph at all. Are you sure this is complete example?

**Comment by richa2008** [comment]
This is the complete example.But I don't know for some reason it is not running here.I am even trying to attach a snapshot of the diagram but I am unable to attach even that also.

**Comment by richa2008** [comment]
Actually I am getting an error after the network diagram is loaded:- Uncaught TypeError: Cannot read property 'ctx' of undefined.
Can you please guess why it is coming.Thank You.

**Comment by anvaka** [comment]
Please use [debugger tool](https://developer.chrome.com/devtools/docs/javascript-debugging) to find where the error happens. If you can provide me with working example - I can take a look.
