### ISSUE TITLE
Image not coming for all the nodes in webgl

### ISSUE THREAD

**Issue by richa2008** [anvaka/VivaGraphJS#117]
Hi,
Can you please provide me with the code of the below example:-
http://www.yasiv.com/facebook
I am trying to add images for nodes with webgl rendering.But the image is not coming for all the nodes.Just a green square box for the nodes and some with the images.

**Comment by anvaka** [comment]
I'm sorry that code is not open. I can hardly recommend writing code in the same style as in http://www.yasiv.com/facebook - it was one of my first web applications and it is very poorly written.

Image wise - facebook visualization renders images only when WebGL is not enabled, using SVG renderer instead, which is much slower..
