### ISSUE TITLE
One extra node coming

### ISSUE THREAD

**Issue by richa2008** [anvaka/VivaGraphJS#119]
Hii..
I am using Vivagraph  for my Network diagram.Everything is working fine with svg rendering.My graph is also coming properly and the text on nodes and links are also getting displayed,except for one thing.

One extra node is coming in the diagram which is static,fixed at one position and not changing with the graph.When I am displaying the text on nodes,text is being displayed on the nodes but along with that all the text data of the nodes is coming on that node also in an overlapping manner.Please help.

**Comment by anvaka** [comment]
use debugger tool and set breakpoint on addNode method. See the stack trace to see who's adding it... You can use node.id to log it to the console.
