### ISSUE TITLE
Search a node

### ISSUE THREAD

**Issue by richa2008** [anvaka/VivaGraphJS#122]
Hi,
I am trying to add search functionality to my graph in which if I pass the id of a node as input then the node with that particular id should be placed centrally.How can I do that.Please help.Thank You.

**Comment by anvaka** [comment]
Use `renderer.moveTo()` method. Here is an [example](http://anvaka.github.io/VivaGraphJS/demos/other/zoomPanAPI.html) and the [source code](https://github.com/anvaka/VivaGraphJS/blob/master/demos/other/zoomPanAPI.html)
