### ISSUE TITLE
give two colors to links

### ISSUE THREAD

**Issue by richa2008** [anvaka/VivaGraphJS#123]
Hi,
Can we give two colors to links.I mean half of the link with one color and half with another color.
Thank You.

**Comment by anvaka** [comment]
Vivagraph does not support this. You can try to implement this by following technique described by Mike Bostok here: [Gradient Along Stroke](https://gist.github.com/mbostock/4163057) but it would probably be very CPU intensive.

**Comment by ryandmonk** [comment]
Not sure if there’s a better place to post, but I have a fiddle that transforms a linear gradient’s start and end positions based on node positions. It’s a little different from Bostock’s version. 
https://jsfiddle.net/ryandmonk/6eg0y19r/1/

**Comment by anvaka** [comment]
@ryandmonk :+1: 

I also learned a trick to use gradient to have a split color:
![image](https://cloud.githubusercontent.com/assets/225407/12107135/b222af0c-b31b-11e5-8328-8912f4a50017.png)

Just add two stops with the same start/stop values in the middle:

``` svg
  <linearGradient id="grad">
    <stop offset="0%" style="stop-color:rgb(255,0,0);stop-opacity:1" />
    <stop offset="50%" style="stop-color:rgb(255,0,0);stop-opacity:1" />
    <stop offset="50%" style="stop-color:rgb(0,0,255);stop-opacity:1" />
    <stop offset="100%" style="stop-color:rgb(0,0,255);stop-opacity:1" />
  </linearGradient>
```

[fiddle](https://jsfiddle.net/6eg0y19r/2/)
