### ISSUE TITLE
Displaying another image beside a node

### ISSUE THREAD

**Issue by richa2008** [anvaka/VivaGraphJS#124]
Hi,
I want to display another image beside every node present in the graph just in the way text comes with nodes.How can I do that.Please help.Thank You.

**Comment by anvaka** [comment]
Use <g> element from SVG spec. [MDN](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/g), [w3](http://www.w3.org/TR/SVG/struct.html#Groups), [VivaGraph example](https://github.com/anvaka/VivaGraphJS/blob/master/demos/tutorial_svg/06%20-%20Composite%20Nodes.html)
