### ISSUE TITLE
adding markers on both the ends of a link

### ISSUE THREAD

**Issue by richa2008** [anvaka/VivaGraphJS#125]
Hi,
I want to add markers on both the ends of the links.I know we can add single marker at one end.But i want to add markers at both the ends.How can I do that.Please help.Thank you.

**Comment by anvaka** [comment]
Please read SVG documentation. There are plenty examples available online: 
* [SVG marker element](http://tutorials.jenkov.com/svg/marker-element.html)
* [MDN](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/marker)

[Google search](https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=svg%20markers) yields a lot of great examples too.
