### ISSUE TITLE
renderer.dispose throws

### ISSUE THREAD

**Issue by ZigGreen** [anvaka/VivaGraphJS#128]
error appears in renderer.js  row #358
``
 publicEvents.removeAllListeners();
``
*TypeError: undefined is not a function*

it seems to be because of 
```
var eventify = require('ngraph.graph');
...
publicEvents = eventify({}),
```
it looks at least strange.

**Comment by anvaka** [comment]
Thank you for reporting this @ZigGreen !

You can also verify it here: [Remove Graph Demo](https://github.com/anvaka/VivaGraphJS/tree/master/demos/other/remove-graph)
