### ISSUE TITLE
Is there a way to start the display of the nodes from top,left of the container?

### ISSUE THREAD

**Issue by Rah1x** [anvaka/VivaGraphJS#129]
Hi,

I am trying to implement viva.graph. However it always show the entire graph at the somewhere below right corner. From firebug it looks like the `g tag` is getting a lot of matrix transformation.

The problem is that I have dynamically increasing/decreasing nodes per view of the page, so I cant override it with 1 single `translate`. So is there a way to have it done?

**Comment by anvaka** [comment]
I'm sorry if I misunderstood your question.

Looks like you are running Firefox and see only quarter of the graph. 

If thats's accurate, then most likely the SVG is missing `width`/`height` attribute. Make sure you change it to `100%`.

[online demo](https://anvaka.github.io/VivaGraphJS/demos/tutorial_svg/06%20-%20Composite%20Nodes.html) | [source code](https://github.com/anvaka/VivaGraphJS/blob/44d8664886808af2e9e8a31e53b2caff03cd21d1/demos/tutorial_svg/06%20-%20Composite%20Nodes.html#L51)

If this is not correct, please provide a jsbin example and I will take a closer look.

**Comment by Rah1x** [comment]
Hi Anvaka... sorry I couldnt explain clearly.

Its not an issue with firefox actually. 

Here is the SVG tag's css:
```
svg {
  width: 500px;
  height: 330px;
}
```
This is what I had to do to bring the entire `group` to visibility:
```$('svg').children('g').attr('transform', 'matrix(1, 0, 0, 1, 250, 230)');````

But you see, if I have a lot and a lot of nodes, this will be still pointless.. Also, if there is just 1 node, its again not exactly best looking.

**Comment by anvaka** [comment]
Yes, that wouldn't scale very well. May I ask you why you need to do this transform? Can you give me an example how graph looks without transform and what's wrong with it?

Thanks!

**Comment by Rah1x** [comment]
Well, without the scale, it would to to outside the visible area in the right-mid.

Here is some part of the code:
```
var graph = Viva.Graph.graph();
//several of nodes added like this graph.addNode('n0', {anchor:'....', label:'....', title:'....', url:'....'});
//paths also added

var graphics = Viva.Graph.View.svgGraphics();
nodeSize = 50;
var layout = Viva.Graph.Layout.forceDirected(graph, {
		springLength : 120,
		springCoeff : 0.0008,
		dragCoeff : 0.02,
		gravity : -1.5
});

graphics.node(function(node)
    {
        var ui = Viva.Graph.svg('g'),

        svgText = Viva.Graph.svg('text').attr('y', '-15px').attr('x', '-' + (nodeSize / 4) + 'px').text(node.data.label);
        //.attr('fill', node.data.color ? node.data.color : '#2CA1F4');

        titleTXT = Viva.Graph.svg('text').attr('y', '-3px').attr('x', '-' + (nodeSize / 4) + 'px').text(node.data.title);
        //.attr('fill', node.data.color ? node.data.color : '#2CA1F4');

        img = node.data.url ? Viva.Graph.svg('image').attr('width', nodeSize).attr('height', nodeSize)
        .link(node.data.url) : Viva.Graph.svg('rect').
        attr('width', nodeSize).attr('height', nodeSize).attr('fill', node.data.color ? node.data.color : '#1A8CE1');

        a = node.data.anchor ? Viva.Graph.svg('a').attr('target', '_blank')
        .attr('href', node.data.anchor) : Viva.Graph.svg('a');
     
        ui.append(svgText);
        ui.append(titleTXT);

        var if_is_me = node.data.is_me;
        if(if_is_me=='1'){
        brdr = Viva.Graph.svg('rect').attr('width', nodeSize).attr('height', nodeSize).attr('fill', '#D7DFE5');
        ui.append(brdr);
        }
        ui.append(img);

        $(ui).dblclick(function(e) {
            window.open(node.data.anchor,'_blank');
        });

        return ui;
    })
    .placeNode(function(nodeUI, pos){
        nodeUI.attr('transform', 'translate(' + (pos.x - nodeSize / 2)+ ',' + (pos.y - nodeSize / 2) + ')');
    });
graphics.link(function(link)
    {
        //alert(dump(link));
        var colortmp = (link.data) && (link.data.color) ? link.data.color: "#1A8CE1"
        return Viva.Graph.svg('path').attr('stroke', colortmp);
    })
    .placeLink(function(linkUI, fromPos, toPos)
    {
		var data = 'M' + fromPos.x + ',' + fromPos.y + 'L' + toPos.x + ',' + toPos.y;
		linkUI.attr("d", data);
    });


//Render Display
    var renderer = Viva.Graph.View.renderer(graph, {
    graphics:graphics,
    layout:layout,
    container: document.getElementById("container_w")
    });
    renderer.run();

$('svg').attr('preserveAspectRatio', 'xMinYMin meet');
```

**Comment by anvaka** [comment]
So, this is your graph: http://jsbin.com/gupeqanaki/1/edit?html,css,js,output - can you reproduce the problem here?

**Comment by Rah1x** [comment]
Ok got it... It was the css that was the issue. I didnt add `position: absolute;` for the SVG tag.
Thanks a lot.
