### ISSUE TITLE
How to avoid vivagraph renders the graph outside of the container?

### ISSUE THREAD

**Issue by lorenzolopez928** [anvaka/VivaGraphJS#130]
i am developing a social network visualization component. I am using the Vivagraph library, but when I add nodes to the forced layout that are not connected to another node, the graph goes outside of the container.

**Comment by anvaka** [comment]
You can add invisible node to your graph, [pin it](http://anvaka.github.io/VivaGraphJS/demos/other/pinNode), and the for each isolated node add invisible edge which connects them to invisible node.

**Comment by lorenzolopez928** [comment]
Thanks,I was thinking already in that, I do it and then I zoomOut the image.
