### ISSUE TITLE
How to make a circular layout with force layout algorithm??

### ISSUE THREAD

**Issue by lorenzolopez928** [anvaka/VivaGraphJS#131]
I need that the layout do not renders any node outside of the container. It is possible?

**Comment by anvaka** [comment]
Looks like you are asking two different questions:

**How to make a circular layout with force layout algorithm?**
I don't think force layout is appropriate tool for this problem. I saw someone was suggesting answer to this question on stackoverflow: [Circular layout in VivaGraphJS](http://stackoverflow.com/questions/18058806/circular-layout-in-vivagraphjs).

**I need that the layout do not renders any node outside of the container. It is possible?**
Only by zooming out ([example 1](http://anvaka.github.io/VivaGraphJS/demos/other/precompute-advanced.html) and [example 2](http://anvaka.github.io/VivaGraphJS/demos/other/zoomPanAPI.html) )
