### ISSUE TITLE
IE issue with Arrows example

### ISSUE THREAD

**Issue by Rah1x** [anvaka/VivaGraphJS#132]
Hi,

I have implemented the arrows example successfully (with the needed modifications). Now its not working with IE.

This is the example I am talking about:
https://github.com/anvaka/VivaGraphJS/blob/master/demos/tutorial_svg/05%20-%20Edges%20With%20Arrows.html

On IE, the arrows and the links dont move around, they just remain static at one place. However, if I dont include this line: `.attr('marker-end', 'url(#Triangle)')` under `graphics.link`
it all works just fine (of course with no arrows). So the issue is with arrows code.

Here is my code (part of it):
```
var graphics = Viva.Graph.View.svgGraphics();
nodeSize = 50;

var layout = Viva.Graph.Layout.forceDirected(graph, {
	springLength : 150,
	springCoeff : 0.0008,
	dragCoeff : 0.102,
	gravity : -1.5
});


//Produce Nodes
graphics.node(function(node)
{
    var ui = Viva.Graph.svg('g'),

    svgText = Viva.Graph.svg('text').attr('y', '-15px').attr('x', '-' + (nodeSize / 4) + 'px').text(node.data.label);

    titleTXT = Viva.Graph.svg('text').attr('y', '-3px').attr('x', '-' + (nodeSize / 4) + 'px').text(node.data.title)
    .attr('fill', node.data.color ? node.data.color : '#2CA1F4');

    img = node.data.url ? Viva.Graph.svg('image').attr('width', nodeSize).attr('height', nodeSize)
    .link(node.data.url) : Viva.Graph.svg('rect').
    attr('width', nodeSize).attr('height', nodeSize).attr('fill', node.data.color ? node.data.color : '#1A8CE1');

    a = node.data.anchor ? Viva.Graph.svg('a').attr('target', '_blank')
    .attr('href', node.data.anchor) : Viva.Graph.svg('a');   

    ui.append(svgText);
    ui.append(titleTXT);    
    ui.append(img);

    $(ui).dblclick(function(e) {
        window.open(node.data.anchor,'_blank');
    });

    return ui;
})
.placeNode(function(nodeUI, pos){
    nodeUI.attr('transform', 'translate(' + (pos.x - nodeSize / 2)+ ',' + (pos.y - nodeSize / 2) + ')');
});


//Produce Arrows (Markers)
var createMarker = function(id) {
return Viva.Graph.svg('marker')
.attr('id', id)
.attr('viewBox', "0 0 10 10")
.attr('refX', "130")
.attr('refY', "5")
.attr('markerUnits', "strokeWidth")
.attr('markerWidth', "11")
.attr('markerHeight', "7")
.attr('orient', "auto");
},
marker = createMarker('Triangle');
marker.append('path').attr('d', 'M 0 0 L 10 5 L 0 10 z');

// Marker should be defined only once in <defs> child element of root <svg> element:
var defs = graphics.getSvgRoot().append('defs');
defs.append(marker);


//Produce Links
graphics.link(function(link)
{
    //alert(dump(link));
    var colortmp = (link.data) && (link.data.color) ? link.data.color: "#1A8CE1"
    return Viva.Graph.svg('path').attr('stroke', colortmp)
    .attr('marker-end', 'url(#Triangle)');
})
.placeLink(function(linkUI, fromPos, toPos)
{
    var data = 'M' + fromPos.x + ',' + fromPos.y + 'L' + toPos.x + ',' + toPos.y; //working - dont delete
    linkUI.attr("d", data);
});


//Render Display
var renderer = Viva.Graph.View.renderer(graph, {
graphics:graphics,
layout:layout,
container: document.getElementById("web_g")
});
renderer.run();
```
I didnt use your enormous `geom` stuff and moved the arrows to the middle of the line so it looks perfect as well as correct (because if you move the link away from the center as in your example, it creates issue for round images with transparent edges). and besides this is much simple.

Here is how it looks on Chrome/Firefox:
![clipboard01](https://cloud.githubusercontent.com/assets/841857/6845972/c9fd49cc-d3db-11e4-9f8f-58623c443d94.png)

And here is how it moves on IE::
![clipboard012](https://cloud.githubusercontent.com/assets/841857/6845999/f9fa5ff2-d3db-11e4-8d0c-1291e5de7571.png)

But if you remove the Marker, it works fine on IE..

**Comment by anvaka** [comment]
Yes, there is a bug in the Internet Explorer, which I opened almost half a year ago: http://connect.microsoft.com/IE/feedbackdetail/view/968203/ie-11-svg-transform-matrix-is-detached-from-svg-element

Unfortunately it was never prioritized by Microsoft.

I'll go ahead and try to come up with workaround.

**Comment by anvaka** [comment]
Actually, the bug that you've reported may not be relevant to the one that I've opened. Its symptoms just look very similar

**Comment by anvaka** [comment]
Found this one, which is exactly what you've reported: https://connect.microsoft.com/IE/feedback/details/801938/dynamically-updated-svg-path-with-a-marker-end-does-not-update

Guys on stackoverflow [suggested to remove and add](http://stackoverflow.com/a/20609600/125351) elements on each update. That is a terrible solution in terms of performance, but I couldn't find anything else. 

You may also want to consider implement your own visual cue to represent a marker, and then on each link position update calculate the mid point of the link, and put your cue there.

**Comment by Rah1x** [comment]
oh... well I've removed `markers` when its `IE`, and keep it there otherwise (hope its working on safari too)...  thats the fastest solution..
:(
