### ISSUE TITLE
Center node problem after precomputation

### ISSUE THREAD

**Issue by bfrgoncalves** [anvaka/VivaGraphJS#136]
Hi,
I am trying to precompute a graph before showing it to the client and then center the graph at a specific node. However, for large graphs or for a great number of iterations, the node is not centered.
I am using layout.step() and then renderer.moveTo() to center the node.

Here is a working example: http://jsbin.com/nufeji/7/edit?html,js,output

Thank you!

**Comment by anvaka** [comment]
Thank you for reporting this. I can reproduce this issue. Will try to fix it as soon as I can. Probably this weekend.

**Comment by bfrgoncalves** [comment]
Thank you. 
I am looking forward to see that fixed.

**Comment by anvaka** [comment]
Please take a look, this should be fixed now.

**Comment by bfrgoncalves** [comment]
Awesome! 
Thx a lot it works perfectly.
