### ISSUE TITLE
Interactive "scroll" throws TypeError

### ISSUE THREAD

**Issue by wehriam** [anvaka/VivaGraphJS#137]
```
Uncaught TypeError: Cannot read property 'onScroll' of undefined
listenToEvents @ vivagraph.js:4585
run @ vivagraph.js:4246
window.onload @ (index):49
```
See: https://jsfiddle.net/pp95tq0s/

Adding `containerDrag = dragndrop(container);` at line 442 of https://github.com/anvaka/VivaGraphJS/blob/master/src/View/renderer.js resolves the issue, but I don't know if that's a good idea.

**Comment by anvaka** [comment]
I think you are right. Thanks for reporting the bug. It should be fixed in `0.7.12`
