### ISSUE TITLE
Tooltip

### ISSUE THREAD

**Issue by ArnauC** [anvaka/VivaGraphJS#138]
Hi! I'm not an expert with JavaScript but I'm working fine with VivaGraphJS, so first of all, thank you for this wonderful library.

I'm creating an application that presents graphic interpretations from social networks information, and I'm stuck in a detail, is there a way for displaying tooltips or any general label with information of the nodes when the mouse hovers on a node?

I'm using webgl graphics, by the way.

Thank you in advance, if you need more information I will provide you!

**Comment by anvaka** [comment]
You can use `webgInputEvents` to monitor mouse activities, here is the demo: https://github.com/anvaka/VivaGraphJS/blob/master/demos/other/webglInput.html 

Then render tooltip yourself at the desired position (using regular DOM elements)
