### ISSUE TITLE
Updating force layout parameters while the layout is running

### ISSUE THREAD

**Issue by julbra** [anvaka/VivaGraphJS#143]
Hello, I'm having a lot of fun with your library plotting large social graphs (~3k nodes ~20k edges with the WebGL renderer).

I'm trying to update the layout parameters once the graph is running but couldn't figure out a clean way of doing this. Currently I'm having to kill the renderer and start afresh every time.

The use case is to have a slider for varying the gravity of the force layout.

**Comment by anvaka** [comment]
This can be done using `layout.simulator`. It [exposes](https://github.com/anvaka/ngraph.physics.simulator/blob/42f1061dca14e0c262b9c8067dab6ff6d1be00a3/index.js#L228) all [config properties](https://github.com/anvaka/ngraph.physics.simulator/blob/42f1061dca14e0c262b9c8067dab6ff6d1be00a3/index.js#L11-L51) as functions. E.g.

``` js
simulator.gravity(-100); // set gravity to -100
```

**Comment by julbra** [comment]
Fantastic worked great thanks a ton!
