### ISSUE TITLE
VivaGraphJS as a R htmlwidget

### ISSUE THREAD

**Issue by timelyportfolio** [anvaka/VivaGraphJS#146]
I thought you might like to be aware that we have started to implement `VivaGraphJS` as a `htmlwidget` in R as part of the `DiagrammeR` package.  Here is a [post](http://www.buildingwidgets.com/blog/2015/5/22/week-20-vivagraphjs-in-diagrammer) describing the initial implemenation.  Thanks so much for all your hard work on `VivaGraphJS` and `ngraph`.

**Comment by anvaka** [comment]
Thank you for letting me know! This is impressive.
