### ISSUE TITLE
Problem with centrality's use

### ISSUE THREAD

**Issue by Istorn** [anvaka/VivaGraphJS#147]
Hello, I've encountered a Problem with the use of centrality's functions: following your example and importing the centrality.js file into my project, during the printing of parameters (beetwennes and degree), the result of everything is only an array filled with generic Object.

Solutions?

**Comment by anvaka** [comment]
Vivagraph prints centrality as array of objects, where each object has two keys:

* `key` - represents node identifier;
* `value` - centrality value, a number

Which example were you following? I'd love to fix it if it is misleading.

**Comment by Istorn** [comment]
I left you the file: <%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
    <%@page import="twitter4j.User"%>
    <%@page import="java.util.ArrayList"%>
<!DOCTYPE html>
<html>
<head>
    <title>Graph Follower</title>
    <script type="text/javascript" src="vivagraph.js"></script>
    <script type="text/javascript">
    <%String img = (String) session.getAttribute("img"); //stringa con l'URL dell utente da cui voglio il graph
    String [] imgfl=new String[500]; 
    String [] imgflfl=new String[500]; //stringa con gli URL dei follower dell'utente
    String [] rname=new String[500]; //stringa riconoscimento flfl
    rname=(String[]) session.getAttribute("rname");
    imgfl=(String[])session.getAttribute("imgfl");
    imgflfl=(String[])session.getAttribute("imgflfl");%>
    
    
    function main () {
        // Step 1. Create a graph:
        var graph = Viva.Graph.graph();
        var img=<%out.print("'"+session.getAttribute("img")+"'");%>;
        
        
        
        
        // Step 2. Add graph content.
        //  graph.addNode(nodeId, yourCustomData) method lets you add new
        //  nodes to the graph and associate them with custom data. In this
        //  case we are associating GitHub user profiles with their Gravatar's images:
        graph.addNode('center', img);
        <% int i=0;int k=0;int m=0; int control=0; while (imgfl[i]!=null)
        {control=0;%>
        imgfl=<%out.print("'"+imgfl[i]+"'");%>;
        link=<%out.print("'li"+i+"'");%>;
       	 graph.addNode(link, imgfl);
         graph.addLink('center', link);
         
         <% 
        	  while (imgflfl[k]!=null && control==0)
        	 {%>
                  imgflfl=<%out.print("'"+imgflfl[k]+"'");%>;
                  link2=<%out.print("'li2"+k+"'");%>;
       	          graph.addNode(link2, imgflfl);
                  graph.addLink(link, link2);
                  
                  <%
        	      if (rname[m]!=rname[m+1])
                	  {
                	      
                	      control=1;
                	      m++;
                	  }
        	      else
        	      {
        	    	  m++;
        	      }
             k++;}
         
         
         
   i++;}%>
        
        	
       
        // Step 3. Customize node appearance.
        //  Vivagraph can present graph in multiple ways. svgGraphics() - is
        //  the way to render graph in SVG format:
        var graphics = Viva.Graph.View.svgGraphics();
        // This function let us override default node appearance and create
        // something better than blue dots:
        graphics.node(function(node) {
            // node.data holds custom object passed to graph.addNode():
            var url = node.data;
            return Viva.Graph.svg('image')
                 .attr('width', 24)
                 .attr('height', 24)
                 .link(url);
        });
        // Usually when you have custom look for nodes, you might want to
        // set their position in a new way too. placeNode() method serves
        // this goal:
        graphics.placeNode(function(nodeUI, pos) {
            // nodeUI - is exactly the same object that we returned from
            //   node() callback above.
            // pos - is calculated position for this node.
            nodeUI.attr('x', pos.x - 12).attr('y', pos.y - 12);
        });
        // Step 4. Render the graph with our customized graphics object:
        var renderer = Viva.Graph.View.renderer(graph, {
                graphics : graphics
            });
        renderer.run();
    }
    </script>

    <style type="text/css" media="screen">
        html, body, svg { width: 100%; height: 100%;}
    </style>
</head>
<body onload='main()'>
<%
out.println("<a href='logout'>Termina ricerca</a>");%>

**Comment by Istorn** [comment]
I left to you the file via message.
