### ISSUE TITLE
Mix VivagraphJS render loop with ThreeJS render loop

### ISSUE THREAD

**Issue by joanitad** [anvaka/VivaGraphJS#154]
Hi,
I'm trying to create a force directed graph using ThreeJS and VivagraphJS. I want the nodes to be particles in a ThreeJS particle system .Is there a way the VivagraphJS render loop can be accessed?
This will allow me to mix the render loop of ThreeJS and VivagraphJS.

Here is my question posted on StackOverflow:
http://stackoverflow.com/questions/31593664/creating-a-3d-graph-using-vivagraphjs-and-using-a-particle-system

I want to achieve something like this in 3D using the ThreeJS particle system .
 http://www.yasiv.com/amazon#/Search?q=graph%20drawing&category=Books&lang=US

Regards,
Joanita

**Comment by anvaka** [comment]
Hi Joanita,

Please consider using [ngraph.pixel](https://github.com/anvaka/ngraph.pixel) which seem to be doing exactly what you are trying to achieve.

Both `vivagraph` and `ngraph.pixel` are sharing the same core.
