### ISSUE TITLE
Disable zoom on mouse scrolling

### ISSUE THREAD

**Issue by ptommasi** [anvaka/VivaGraphJS#157]
Is there a way to disable zoom on mouse scrolling? I do have a graph as part of a scrollable view, and when (during the scroll) the mouse end up on top of a graph the view stop to scroll and a zoom take place instead.

It would be useful to have a boolean options in the renderer with a behaviour similar to "mouseWheelZoom" or ".disableZoomWheel()" of OpenLayers3 (that's how I solved the same issue with it).

Thanks!

**Comment by gg4u** [comment]
Hi,

if you look into vivagraph.js, you will see that there is a parameter:
interactive

it accept strings and an array of strings as parameters, 

so you could deactivate as you wish:

Have a look here:
https://github.com/anvaka/VivaGraphJS/tree/master/demos/other/input-override#no-interaction

**Comment by ptommasi** [comment]
That solve my problem, I wasn't aware of that parameter! 

Thanks very much!
