### ISSUE TITLE
How to add a click event?

### ISSUE THREAD

**Issue by JantineD** [anvaka/VivaGraphJS#167]
How can I add an click event to a node to show more info in a popup with jquery?

**Comment by anvaka** [comment]
Hi @JantineD,

Here is an example for [SVG](https://github.com/anvaka/VivaGraphJS/blob/master/demos/tutorial_svg/04%20-%20Listen%20To%20Mouse%20Events.html), and for [WebGL](https://github.com/anvaka/VivaGraphJS/blob/master/demos/other/webglInput.html).
