### ISSUE TITLE
Is rendering 1 million nodes and links possible?

### ISSUE THREAD

**Issue by lieutenant** [anvaka/VivaGraphJS#174]
I love Vivagraph but is it possible to render up to a million nodes and edges? I'm using custom nodes and links and rendering 20k nodes/links kills the frame rate. Are there any ways to speed up or optimize it to handle 1 million nodes?

**Comment by anvaka** [comment]
The only way I'm aware of is to use offline layout, used here: https://github.com/anvaka/pm it has description how to get started.

**Comment by tyn1998** [comment]
> The only way I'm aware of is to use offline layout, used here: https://github.com/anvaka/pm it has description how to get started.

OMG! Just AMAZING!
