### ISSUE TITLE
Vivagraph gets two different sets of data and visualize from time to time

### ISSUE THREAD

**Issue by mj-fintech** [anvaka/VivaGraphJS#197]
Hi,

The issue is this,

I am building a Flask web with Python.

I am defining a page for the network visualization, which is "networks.html" like the code below
```
@app.route('/networks')
def market_networks_page():
	all_ticker = full_list
	linkdata = networksdata
	return render_template("networks.html", all_ticker=all_ticker, linkdata=linkdata)
```

The linkdata is the data to be used by Vivagraph to visualize the network. 
The linkdata is in this form -->
[{'source': node1, 'target': node2, 'weight': 0.933333}, {'source': node13, 'target': node22, 'weight': 0.88333}, ....................]

And in javascript, I am adding the links by doing this -->
```
for (i = 0; i<linkdata.length; i++) {
        graph.addLink(linkdata[i]['source'],linkdata[i]['target']);
        };
```
 
It works fine, it visualizes the network correctly. But the thing is that the "linkdata", in python back-end, get updated every 30 minutes. So every 30 minutes networks.html shows a different networks as the data is updated.

The thing is that when I refresh this page some times it shows the correct network but some times it shows previous network while I only have the new set of linkdata and not having the previous linkdata. Shouldn't it always show the latest network? When I refresh the page, it shows correct one, and when I refresh the page again, it shows previous network. 

as you can see from the attached image, it still contains the two different datasets and from time to time, it uses one of them randomly. I don;t know why it happens. Based on my Python backend, it only passes one set of data (linkdata) to the javascript.

![sample11](https://cloud.githubusercontent.com/assets/19509670/25405201/8986815e-29d0-11e7-9c7f-6cd518210528.png)
When I refresh the page, and in the console, linkdata has 1,239 links, but when I refresh again it uses other dataset which contains 1,516 links. How should I take care of this issue?

**Comment by anvaka** [comment]
sounds like your browser or server caches data. Consider disabling cache on the server or add a unique query string attribute to your data endpoint (e.g. index?timestamp=1235)
