### ISSUE TITLE
Tree Layout

### ISSUE THREAD

**Issue by sivix** [anvaka/VivaGraphJS#20]
How would be possible having a Tree-like layout?
Something like this:
http://mbostock.github.com/d3/talk/20111018/tree.html

Thanks,
Andrea.

**Comment by schaveyt** [comment]
What this closed because it has been implemented or abandoned?

**Comment by anvaka** [comment]
@schaveyt it was not implemented. If you need hierarchical layouts you can try https://github.com/cpettitt/dagre or https://github.com/tgdwyer/WebCola
