### ISSUE TITLE
Strange visual problem with animation  

### ISSUE THREAD

**Issue by DigitalD1982** [anvaka/VivaGraphJS#213]
Hi there!

I can't seem to figure out why I'm getting these strange white lines on the left of my chart. It doesn't seem to be an actual object in the DOM. I may be wrong about that though. This is reproducible on multiple machines so it's not a monitor thing. Has anyone ever seen this before?

If it helps this chart is using the forceDirected layout.

https://www.dropbox.com/s/6fk73is4eflcxju/WeirdArtifacting.mov?dl=0

**Comment by anvaka** [comment]
Would it be possible to share a link to code where I could reproduce it?

Do you guys see it consistently across different browsers?

Those machines have the same OS? How about video adapter?

**Comment by DigitalD1982** [comment]
Hey Andrei, thanks for the quick response. It's all running in Electron actually. I'm not able to reproduce outside of electron. All machines that have been tested are Macs. Either the new Macbook pros or a desktop Mac Pro.

Sadly I'm not be able to share the code. This might be 100% something on our end but I wanted to check here first if you've seen this before.

Amazing charts btw! Kudos

**Comment by DigitalD1982** [comment]
And like that I found the fix. Adding this to the container div fixed the problem.

-webkit-backface-visibility:hidden;

Tip came from here.
https://greensock.com/forums/topic/6533-how-to-fix-rendering-artifacts-in-chrome/

Thanks Again!
