### ISSUE TITLE
Could you share real projects repo for us demo?

### ISSUE THREAD

**Issue by jkryanchou** [anvaka/VivaGraphJS#214]
Hi @anvaka, I found that those real projects you mentioned in REAMDE were so cool. Could you share them for us to learn. They would be a good examples for get started with VivaGraphJS.

**Comment by balaji97** [comment]
The project repositories are available on his github profile.

**Comment by anvaka** [comment]
https://github.com/anvaka/yasiv-youtube is publicly available as well. I'm not ready to share remaining visualizations from the Readme file yet.

**Comment by jkryanchou** [comment]
@anvaka OK, Cool I have already read about it yet. It looks so cool. And it was also built with the Vue.js framework which was my favourite.
