### ISSUE TITLE
Cannot Set svg element size

### ISSUE THREAD

**Issue by xswei** [anvaka/VivaGraphJS#224]
when use svgGraphics, the svg size cannot be set, default is 300x150. can export a parameter to set svg's size, such as : 
 `var graphics = Viva.Graph.View.svgGraphics({
      width: 500,
      height: 500
  })`

**Comment by gg4u** [comment]
`Graphics` is a parameter of a rendering object, which also has a `container`parameter that is the html object where the graph is rendered.

You can use HTML5 style to modify the size of graph:

```
      renderer = Viva.Graph.View.renderer(graph, {
          layout    : layout,
          graphics: graphics,
          container : document.getElementById('yourGraphContainer')
      });

```
```
// html
document.getElementById("yourGraphContainer").style.width = "500px";
document.getElementById("yourGraphContainer").style.height = "500px";
```
