### ISSUE TITLE
Display node attribute on mouse event in WebGl

### ISSUE THREAD

**Issue by qdelettre** [anvaka/VivaGraphJS#27]
Hi,

I am trying to understand the library and webgl. I would like to display node text attributes on mouse over event, in webgl. 

The use case would be that : user put the mouse cursor on a node, the text attribute of a node appear over it. The text disappear as the cursor is no longer on the node.

How can i have access to the canvas and its context ?
Can i use the fillText function to draw the text ?

Thanks

**Comment by anvaka** [comment]
You can find webgl input handling demo [here](https://github.com/anvaka/VivaGraphJS/blob/master/demos/other/webglInput.html)
