### ISSUE TITLE
trying to add text to a node

### ISSUE THREAD

**Issue by codingAlchemist** [anvaka/VivaGraphJS#33]
var graphics = Viva.Graph.View.svgGraphics();
graphics.node(function(node){

```
         var text = Viva.Graph.svg('text')
          .attr('text-anchor', 'middle')
          .attr('stroke','green')
          .attr('font-size', 24)
          .text('Jason')

          var label =  Viva.Graph.svg('rect')
          .attr('stroke-width', 10)
          //.attr('stroke', 'red')
          .attr('width', 24)
          .attr('height', 24)

          label.append(text);
          return label;
          });
```

var renderer = Viva.Graph.View.renderer(g,{
        graphics : graphics
    });

above is my code, but i am not getting any text to show

**Comment by apivovarov** [comment]
@anvaka  how to display node text with webglGraphics?

**Comment by anvaka** [comment]
You can use DOM labels:
http://anvaka.github.io/VivaGraphJS/demos/other/webglDOMLabels.html -
unfortunately there is no WebGL text support;
Source code:
https://github.com/anvaka/VivaGraphJS/blob/master/demos/other/webglDOMLabels.html

**Comment by apivovarov** [comment]
ok it works!
@anvaka How to implement showing label on node mouseover only (on svg or webgl)
similar to here http://www.yasiv.com/amazon#/Search?q=graph%20drawing&category=Books&lang=US

**Comment by apivovarov** [comment]
ok add added hover as described here https://github.com/anvaka/VivaGraphJS/blob/master/demos/tutorial_svg/04%20-%20Listen%20To%20Mouse%20Events.html

And set short or full text to svg text

**Comment by apivovarov** [comment]
Next question is to how add right panel with detailed node info?
similar to here http://www.yasiv.com/amazon#/Search?q=graph%20drawing&category=Books&lang=US
