### ISSUE TITLE
Pictures for nodes in WebGL

### ISSUE THREAD

**Issue by duckwc** [anvaka/VivaGraphJS#34]
I'm not able to use pictures in a webGL force directed graph I made.
My graph is over 1,000 nodes, so I can't really use another rendering method.
Is it possible or do you have plan to add this feature?

**Comment by rmtom** [comment]
I'm using vivagraph for a couple of years, I just started trying use webgl now, because I have some big graphics to display... I wonder if there's code example using webglImageNodeProgram .  I tried the code from TDonselaar above, but for a strange reason the image don't stay in correct position, it seems reflect in horizontal axis, the edges up and images down.

**Comment by sapnarani** [comment]
Nice blog, i like this great post and your thoughts.
http://www.bangalorehotcallgirls.in/

**Comment by suratnew2016** [comment]
Surat escort Service –  http://www.secretcorner.in/
High profile call girl service - - http://www.secretpartner.in/
Rajkot Escort Service –  http://www.ask4callgirl.com/
All India Escort Service - -  http://www.bookacallgirl.com/
Vadodara Escort Service --  http://www.secretfun.in/
Jaipur Escort Service -  http://www.secretcorner.in/
Goa Escort --  http://www.secretrelation.in/
Ahmedabad Call Girl Service -- http://www.secretlove.in/
Kolkata Escort - - http://www.kolkataqueen.in/

**Comment by suratnew2016** [comment]
Bhubaneswar Escort ---
http://www.citycallgirl.com/

**Comment by weequ** [comment]
I'm having the same issue as rmton. It works correctly in the middle of the horizontal axis but when I drag up the images move down and vice-versa.

**Comment by josephrocca** [comment]
Here's a fixed version of 0.10.0 per weequ's edits in the pull request linked above:

https://gist.github.com/josephrocca/a5e3bfb96665ef5e5499523e2cc71cb7
