### ISSUE TITLE
get rid of huge returns objects in vivagraph

### ISSUE THREAD

**Issue by antonkulaga** [anvaka/VivaGraphJS#40]
In most of viva-graph classes  there are some operations and variables in the beginning and than a return statement that returns a huge object.

The problem with that approach is that it makes vivagraph completely unextendable, you have to rewrite the whole module if you want just to override one or several methods =(( 

I suggest to use normal classes in vivagraph. So developers will be able to do something like:

``` coffee-script
class MyCustom graph extends VivaGraph.Graph

someMethodToOverride: ->
 super
 somecustomcode()
```

**Comment by gg4u** [comment]
hi @anvaka,

could you show an example for using vivagraph with angular?
I wrote a web-app with vivagraph, hammerjs and jquery.
Angular is not really straight forward for me, I am learning with a dive course about angular-cli:
https://www.udemy.com/learn-angular-from-scratch/learn/v4/t/lecture/6976310?start=0

and I would be happy to wrap the whole piece of code within a "graph" view. 

It would be nice if you or someone savvy with angular could show an example to fit with above tutorial.
