### ISSUE TITLE
is it possible to store additional information in node than its data and id

### ISSUE THREAD

**Issue by jagandeep** [anvaka/VivaGraphJS#49]
I have system where multiple type of node are present and these nodes can have different status( active, inactive or others) . Is it possible to store this information in a node instance. I am using the node type for link. I want to display different images based on the statues of the node.

**Comment by anvaka** [comment]
Sure, you can do:

``` javascript
graph.addNode('nodeId', {
  status: 'active',
  title: 'your title',
  // etc...
});
```

See more info [here](https://github.com/anvaka/ngraph.graph/blob/master/README.md#what-to-use-as-nodes-and-edges)
