### ISSUE TITLE
directed graph support

### ISSUE THREAD

**Issue by inf3rno** [anvaka/VivaGraphJS#50]
Is it possible to display directed graphs with vivagraph?

**Comment by anvaka** [comment]
Yes, you can use SVG arrows to get this effect: [Demo](http://anvaka.github.io/VivaGraphJS/demos/tutorial_svg/05%20-%20Edges%20With%20Arrows.html), [Source](https://github.com/anvaka/VivaGraphJS/blob/master/demos/tutorial_svg/05%20-%20Edges%20With%20Arrows.html)
