### ISSUE TITLE
decorating images on nodes are all replaced with first in Firefox, Safari iPad (rotation), Chrome Dev

### ISSUE THREAD

**Issue by gg4u** [anvaka/VivaGraphJS#56]
Hi,
I got this bug:
I decorate nodes with external images.
When I use the dev console in Chrome, I see all images are changed and become all the same.

I thought it was a behavior of console, but instead I have the same issue in iPad when I rotate the device 90°
and firefox.

Anybody met the same issue?
Can't figure out what it is...

**Comment by anvaka** [comment]
Hi @gg4u . I'm going through old issues and found this. Sorry for dropping the ball. I saw your demos and think you have figured out the solution? 

Going to close this issue now, but feel free to reopen if you still experience this problem.
