### ISSUE TITLE
Graph Inside Div

### ISSUE THREAD

**Issue by sherlholmes** [anvaka/VivaGraphJS#6]
I am trying to render the Graph inside a div. Not able to figure it out.
How to put the graph in the div?

**Comment by Clay-Ferguson** [comment]
@anvaka This is probably going to be a popular question. You may want to therefore address this question right at the beginning of your first example. Thanks! looking forward to trying this out. Looks awesome!

**Comment by anvaka** [comment]
@Clay-Ferguson thanks! [fixed](https://github.com/anvaka/VivaGraphJS/commit/a21c6b56fd5937c29cfe6a74943ab4a2d829b07a)

**Comment by Clay-Ferguson** [comment]
I tried to run it, and it renders a canvas object that's 1px by 1px. Not sure what i'm doing wrong. I'm sure I have the JS file loading correctly but not working yet.

**Comment by anvaka** [comment]
check the CSS for the div - does it have width/height?

**Comment by Clay-Ferguson** [comment]
I tried again, but still can't get it. Here's the code:
I am sure the DIV exists, and has size 500x500px, and the vivaGraph.js is
definitely getting found and loaded correctly.
(So something's gotta be missing? Are there other dependecies? I have
jquery and polymer and lots of other javascript, BTW,
so maybe I should try on a blank page or something and get it running there
first).

I didn't (nor will I) run any command line code. ALL i'm doing is including
your JS file, right?

                        var graph = Viva.Graph.graph();
                        graph.addLink(1, 2);
///////////////
//var graphGenerator = Viva.Graph.generator();
//var graph = graphGenerator.grid(3, 3);

// var layout = Viva.Graph.Layout.forceDirected(graph, {
//    springLength : 10,
//    springCoeff : 0.0005,
//    dragCoeff : 0.02,
//    gravity : -1.2
// });

var graphics = Viva.Graph.View.webglGraphics();
var container = document.getElementById('searchResultsPanelSub');
if (container==null) {
console.log("container is null in viva!");
return;
}
var renderer = Viva.Graph.View.renderer(graph, {
container : container,
graphics : graphics//,
//layout : layout
});
renderer.run();

Best regards,
Clay Ferguson
wclayf@gmail.com
