### ISSUE TITLE
Renderer for Graphviz graphs?

### ISSUE THREAD

**Issue by PapyRef** [anvaka/VivaGraphJS#61]
Is it possible to display Graphviz graphs (xdot renderer) with vivagraph? 

Example of Graphviz dot file

digraph G {
0 [label="A"];
1 [label="B"];
2 [label="C"];
3 [label="D"];
4 [label="E"];
0 -> 1 [ ];
0 -> 3 [ ];
1 -> 2 [ ];
1 -> 4 [ ];
2 -> 3 [ ];
3 -> 4 [ ];
}

**Comment by anvaka** [comment]
Just a small update. While VivaGraph does not support dot files parsing, I'm working on a separate project which would eventually let us implement dot files rendering: https://github.com/anvaka/dotparser 

It will be part of [ngraph](https://github.com/anvaka/ngraph) family. VivaGraph starting from version 0.7 will be built from ngraph modules as well, which gives great potential for code reuse.
