### ISSUE TITLE
Force Atlas 2

### ISSUE THREAD

**Issue by arikan** [anvaka/VivaGraphJS#70]
It would be great to have Force Atlas 2 algorithm implemented for layouts. Here is a version implemented in Javascript:
https://github.com/jacomyal/sigma.js/tree/master/plugins/sigma.layout.forceAtlas2

**Comment by anvaka** [comment]
I'm adding this to my todo list in the `ngraph` family: https://github.com/anvaka/ngraph/blob/master/plan/01%20-%20todo.md

**Comment by brienna** [comment]
+1 to adding ngraph.forceatlas2 or carrying over https://github.com/ZigGreen/ngraph.forceAtlas2 so that it can work with ngraph.offline.layout
