### ISSUE TITLE
Restricting graph on the webpage

### ISSUE THREAD

**Issue by shubhag** [anvaka/VivaGraphJS#80]
Sometimes the graph moves out of the screen as shown by the image. I want to know if it is possible to restrict it within the area assigned to it on the webpage
![a](https://f.cloud.github.com/assets/5223357/2524707/a00904ea-b4e6-11e3-8ef5-4e5f44ef599b.png)

**Comment by audoeyop** [comment]
I couldn't tell form that example how to pin the 1st node.  Could you please write a code snippet example of how to pin the 1st node?
