### ISSUE TITLE
Getting zoom levels 

### ISSUE THREAD

**Issue by arikan** [anvaka/VivaGraphJS#84]
Since we have the `renderer.zoomIn()` and `renderer.zoomOut()` functionality, I think it is necessary to store and get the zoom level info from the renderer from a function  like `renderer.getZoomLevel()`

Although this has been discussed before https://github.com/anvaka/VivaGraphJS/issues/17, there was no practical solution. Zoom level information would be useful for scaling graphics and text based on the zoom level, which would also help with rendering performance on big graphs.

**Comment by mzachariadis** [comment]
Hello Andrei, 

is their any way to get the zoom level without calling renderer.zoomIn/Out() methods? 

Thanks!

**Comment by anvaka** [comment]
Hi Mike, I've just added `renderer.getTransform()` - please let me know if that helps.

It should be available in `v0.10.1`

**Comment by mzachariadis** [comment]
Yeap! This is what I was looking for. Many thanks!
