### ISSUE TITLE
Returning to force layout after pinning nodes

### ISSUE THREAD

**Issue by doodnayr** [anvaka/VivaGraphJS#92]
Not sure if this really counts as an issue, but I'm not sure how to deal with it. If I pin some nodes and programmatically set their positions, the remaining unpinned nodes do not respond by force layout to the pinned nodes' new positions until I interact with the graph again. I believe this is because the algorithm sees the graph as stable because no nodes were moving when the programmatic setting of some nodes' positions happened. Is there a way to restart the force layout algorithm when no nodes are moving?

**Comment by anvaka** [comment]
Thank you @zrlram
